version: "2"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
    - .:/usr/src/app/
    ports:
    - "3000:5001"
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo:2.6.10
    volumes:
    - ~/Downloads/data:/data/db
    ports:
    - "27017:27017"
